<div class="contentHeader">
<img src="<?php echo $this->baseUrl()?>/media/img/KarteContent.png" alt="Viesunams Sidrabi Karte" /><h2>Par Sidrabiem</h2>
</div>
<div id="sml-01"></div>
<div id="sml-02"></div>
<div id="sml-03"></div>
<div id="sml-04"></div>
<div id="sml-05"></div>
<div id="sml-06"></div>
<div id="sml-07"></div>
<div id="sml-08"></div>
<div id="sml-09"></div>
<div id="sml-10"></div>
<div id="sml-11"></div>


<p>Adrese: "Sidrabi", Saldus raj., Saldus pagasts, LV-3862, Latvija</p>

<p>Zemāk esošajā kartē redzams, kā pie mums nokļūt:</p>

<div><img src="<?php echo $this->baseUrl()?>/media/img/map.gif" alt="karte parādīts kā nokļūt līdz sidrabiem" /></div>