<div class="contentHeader">
<img src="<?php echo $this->baseUrl()?>/media/img/Kontakti.png" alt="Viesunams Sidrabi kontakta informācija" /><h2>Par Sidrabiem</h2>
</div>
<div id="sml-01"></div>
<div id="sml-02"></div>
<div id="sml-03"></div>
<div id="sml-04"></div>
<div id="sml-05"></div>
<div id="sml-06"></div>
<div id="sml-07"></div>
<div id="sml-08"></div>
<div id="sml-09"></div>
<div id="sml-10"></div>
<div id="sml-11"></div>

<p> Lūdzu zvaniet pa talruni (371) 29743909 vai rakstiet uz ē-pasta adresi <a href="mailto:info@sidrabi.com">info@sidrabi.com</a></p>
