<div class="contentHeader">
<img src="<?php echo $this->baseUrl()?>/media/img/Pakalpojumi.png" alt="Viesunams Sidrabi pakalpojumi" /><h2>Par Sidrabiem</h2>
</div>
<div id="sml-01"></div>
<div id="sml-02"></div>
<div id="sml-03"></div>
<div id="sml-04"></div>
<div id="sml-05"></div>
<div id="sml-06"></div>
<div id="sml-07"></div>
<div id="sml-08"></div>
<div id="sml-09"></div>
<div id="sml-10"></div>
<div id="sml-11"></div>


<p class="specialCase" style="margin-top:15px">Galda klāšana viesībām - Ēdināšana </p>
<div class="specialUl"><ul class="listDocor">
<li style="margin-left:220px">kāzu svinības</li>
<li style="margin-left:200px">banketi</li>
<li style="margin-left:180px">brokastis</li>
<li style="margin-left:150px">vakariņas</li>
</ul>
</p>
</div>

<div class="sliderWrap">
<div id="slider">
		<ul>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/pakalpojumi/31.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/pakalpojumi/32.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/pakalpojumi/33.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/pakalpojumi/34.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/pakalpojumi/35.jpg" alt="Css Template Preview" /></a></li>			
		</ul>
	</div>
</div>

<p class="specialCase" style="margin-top:30px; margin-left:15px; line-height: 1.2;">Jaunā Pāra un Kāzu viesu sagaidišana</p>
<p class="specialCase" style="margin-top:30px; margin-left:15px; line-height: 1.2";>Brīvdabas izrādes kopā ar Druvas amatieru teātri un deju kopu iesaistot pašus viesus</p>  
<p class="specialCase" style="margin-top:30px; margin-left:15px;line-height: 1.2;margin-bottom:30px;">Vienu dienas ekskursijas pa ievērotākajiem objektiem(vācu, angļu gidi ir pieejami)</p> 

<br/></br>