<div class="contentHeader">
<img src="<?php echo $this->baseUrl()?>/media/img/ParSidrabiem2.png" alt="Par Sidrabiem" /><h2>Par Sidrabiem</h2>
</div>
<div id="sml-01"></div>
<div id="smr-01"></div>
<div id="sml-02"></div>
<div id="smr-02"></div>
<div id="sml-03"></div>
<div id="smr-03"></div>
<div id="sml-04"></div>
<div id="smr-04"></div>
<div id="sml-05"></div>
<div id="smr-05"></div>
<div id="sml-06"></div>
<div id="smr-06"></div>
<div id="sml-07"></div>
<div id="smr-07"></div>
<div id="sml-08"></div>
<div id="smr-08"></div>
<div id="sml-09"></div>
<div id="smr-09"></div>
<div id="sml-10"></div>
<div id="smr-10"></div>
<div id="sml-11"></div>
<div id="smr-11"></div>
<div id="sml-12"></div>
<div id="smr-12"></div>
<div id="sml-13"></div>
<div id="smr-13"></div>
<div id="sml-14"></div>
<div id="smr-14"></div>
<div id="sml-15"></div>
<div id="smr-15"></div>
<div id="sml-16"></div>
<div id="smr-16"></div>
<div id="sml-17"></div>
<div id="smr-17"></div>
<div id="sml-18"></div>
<div id="smr-18"></div>
<div id="sml-19"></div>
<div id="smr-19"></div>
<div id="sml-20"></div>
<div id="smr-20"></div>
<div id="sml-21"></div>
<div id="smr-21"></div>
<div id="sml-22"></div>
<div id="smr-22"></div>
<div id="sml-23"></div>
<div id="smr-23"></div>
<div id="sml-24"></div>
<div id="smr-24"></div>
<div id="sml-25"></div>
<div id="smr-25"></div>
<div id="sml-25a"></div>
<div id="smr-25a"></div>
<div id="sml-26"></div>
<div id="smr-26"></div>
<div id="sml-27"></div>
<div id="smr-27"></div>
<div id="sml-28"></div>
<div id="smr-28"></div>
<div id="sml-29"></div>
<div id="smr-29"></div>
<div id="sml-30"></div>
<div id="smr-30"></div>
<div id="sml-31"></div>
<div id="smr-31"></div>
<br>
 <p class="specialCase">Te ir gals visiem ceļiem – vieta, kur patverties no pilsētas burzmas un kņadas..... Vieta, 
 kur daba vienojas ar cilvēkiem - caur plaukstošu bērzu pumpuru smaržu tuvējā birzstalā, caur 
 lakstīgalas skanīgo trelli ievziedu kupenā, caur ziedošu pieneņu medaino smaržu un svēteli, 
 kas apciemos Jūs ik dienu.</p>
 <p class = "specialCase2">Aicinām cilvēkus, kas mīl dabu, priecīgus cilvēkus un pilsētas nogurdinātos,  mazas kompānijas 
 ( līdz 30 pers) un kāziniekus (līdz 50 pers), ērtību un komforta mīļotājus un mīlētājus, mieru un 
 klusumu mīlošus vai skaļus un aktīvu atpūtu cienošus – visus atpūtas gribētājus laipni uzņemsim atsevišķā, 
 tikai viesiem paredzētā  mājā līdz 15 pers. vai divos 2-vietīgos brīvdienu dzīvokļos.</p>
<br><br>

<p class = "specialCase2">Viesu rīcība ir trīs dažādas viesību zāles, labiekārtota virtuve, pirts, bērnu rotaļu un sporta laukumi, 
 bērzu birzītē ierīkota piknika vieta.</p>
 
<p class = "specialCase2" >Lai iegūtu vairāk informacijas par māju, dzivokļiem, viesību zālēm, pirti un parējo aicinām skatīt <a href="/main/home?saturs=Piedavajumi">Piedāvajumus</a> </p>

<p class = "specialCase2">Sidrabu viesiem ir arī peejams pašas saimnieces uz vietas gatavotie un daudzu slavētie ēdieni viesībām vai jebkurai ēdienu reizei. Lai uzzinātu vairāk par galda klāšanu viesībām - ēdināšanu aicinām skatīt <a href="/main/home?saturs=Pakalpojumi">Pakalpojumus</a> </p>


