<div class="contentHeader">
<img src="<?php echo $this->baseUrl()?>/media/img/Piedavajumi.png" alt="Viesunams Sidrabi Piedāvā" /><h2>Par Sidrabiem</h2>
</div>
<div id="sml-01"></div>
<div id="sml-02"></div>
<div id="sml-03"></div>
<div id="sml-04"></div>
<div id="sml-05"></div>
<div id="sml-06"></div>
<div id="sml-07"></div>
<div id="sml-08"></div>
<div id="sml-09"></div>
<div id="sml-10"></div>
<div id="sml-11"></div>
<p class="specialCase" style="position:relative;top:30px; left:10px;"> Viesu māja "Sidrabi" ir atsevišķa māja viesiem, kuras aprīkojumā ir viss nepieciešamais jaukai atpūtai gan 
vasarā, gan ziemā:</p>
<div class="sliderWrap">
<div id="slider">
		<ul>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/01.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/02.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/03.jpg" alt="Css Template Preview" /></a></li>
		</ul>
	</div>
</div>
<ul class="listDocor">
<li>sešas labiekārtotas viesu guļamistabas, kas izvietotas nama 1. un 2.stāvos, katrā stāvā duša un WC</li>
</ul>
<div class="sliderWrap2">
<div id="slider2">
		<ul>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/04.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/18.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/05.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/06.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/07.jpg" alt="Css Template Preview" /></a></li>
		</ul>
	</div>
</div>
<ul class="listDocor">
<li>pilnībā labiekārtota virtuve, kur viesi paši var gatavot maltīti. Aprīkojumā ietilpst- elektriskā plīts ar 
cepeškrāsni, trauku mazgājamā mašīna, ledusskapis, veļas automāts, mikroviļņu krāsns, ir visi nepieciešamie trauki un virtuves inventārs</li>
</ul>

<div class="sliderWrap3">
<div id="slider3">
		<ul>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/08.jpg" alt="Css Template Preview" /></a></li>
		</ul>
	</div>
</div>
<ul class="listDocor">
<li>ar izsmalcinātu dizainu izceļas dzīvojamā istaba, kur kamīnā rotaļājas dzīvas  uguns mēles, kurā atrodas klavieres un virpotas koka mēbeles</li>
</ul>
<div class="sliderWrap4">
<div id="slider4">
		<ul>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/09.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/10.jpg" alt="Css Template Preview" /></a></li>
		</ul>
	</div>
</div>
<ul class="listDocor">
<li>mājas pagrabstāvā atrodas neliela zāle svinībām līdz 30 personām un</li>
</ul>
<div class="sliderWrap5">
<div id="slider5">
		<ul>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/11.jpg" alt="Css Template Preview" /></a></li>
		</ul>
	</div>
</div>
<ul class="listDocor">
<li>slapjā lauku pirts ar malkas apkuri, kurā sienas un lāvas darinātas no liepas koka, lai būtu vieglāks gars. Pirts priekiem tiek piedāvātas</li>
<li>dažādas pirtszāļu slotiņas</li>
</ul>
<div class="sliderWrap6">
<div id="slider6">
		<ul>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/12.jpg" alt="Css Template Preview" /></a></li>
		</ul>
	</div>
</div>

<ul class="listDocor">
<li>mājas terasē ērti uztaisīt barbekjū, pabaudīt vakara saulrietu, vai papriecāties par ziedu bagātību un 
košumu saimnieces ierīkotajās puķudobēs</li>
</ul>
<div class="sliderWrap7">
<div id="slider7">
		<ul>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/13.jpg" alt="Css Template Preview" /></a></li>
		</ul>
	</div>
</div>
<ul class="listDocor">
<li>viesu ērtībai un labsajūtai blakusesošajā bērzu birzī ierīkota piknika- ugunskura vieta</li>
</ul>

<div class="sliderWrap8">
<div id="slider8">
		<ul>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/16.jpg" alt="Css Template Preview" /></a></li>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/14.jpg" alt="Css Template Preview" /></a></li>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/15.jpg" alt="Css Template Preview" /></a></li>
		</ul>
	</div>
</div>

<p>Jūs varēsiet izmantot arī labiekārtotu bērnu rotaļu laukumu un sporta spēļu (volejbola, futbola) laukumus.</p>

<div class="sliderWrap9">
<div id="slider9">
		<ul>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/17.jpg" alt="Css Template Preview" /></a></li>				
		</ul>
	</div>
</div>

<p>Māju var iznomāt visu kopā vienlaicīgi līdz 15 personām (150ls/diennakts), cenā ietilpst arī mazā zāle kopā ar pirti vai arī 
<ul class="listDocor">
<li>var īrēt atsevišķas istabas(15ls par vienu 2vietīgu istabu /diennaktī)</li> 
<li>bet cenas elastīgas atkarībā no viesu skaita un izvēlētās atpūtas ilguma. Cenā nav iekļautas brokastis
</li>
</ul>

 <p class="specialCase" style="margin-left:15px">Brīvdienu dzīvokļi</p>
 <ul class="listDocor">
<li>piedāvājam divus vienistabas brīvdienu dzīvokļus, kuri atrodas citā ēkā, bet viesu nama teritorijā ar skaistu 
skatu uz dārzu. Dzīvokļi labiekārtoti, ir guļamā, atpūtas un virtuves zona, duša un WC. Katram dzīvoklim ir sava 
lauku terase. Dzīvokļi paredzēti divām personām-cena 20ls/diennaktī. Cenā neietilpst brokastis.</li></ul>
<p style="margin-left:15px" class="specialCase">Telpas svinībām un semināriem:</p>
<ul class="listDocor">
<li>mazā zāle (30 pers) kopā ar slapjo pirti uz 12 stundām- 60ls</li>
</ul>

<div class="sliderWrap10">
<div id="slider10">
		<ul>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/19.jpg" alt="Css Template Preview" /></a></li>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/20.jpg" alt="Css Template Preview" /></a></li>				
		</ul>
	</div>
</div>


<ul class="listDocor">
<li>zāle semināriem vai lielākām viesībām (50pers.) kopā ar daļēji segtu lielu lauka nojumi. 10ls/stundā, vai 100ls diennaktī</li>
</ul>

<div class="sliderWrap11">
<div id="slider11">
		<ul>
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/22.jpg" alt="Css Template Preview" /></a></li>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/23.jpg" alt="Css Template Preview" /></a></li>				
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/21.jpg" alt="Css Template Preview" /></a></li>	
			<li><a href=""><img src="<?php echo $this->baseUrl()?>/media/img/piedavajumi/24.jpg" alt="Css Template Preview" /></a></li>	
		</ul>
	</div>
</div>

<p>Mazākam cilvēku skaitam dodam atlaides.</p>
<p>Vienlaicīgi varam nakšņošanu nodrošināt 20pers., ar papildvietām 30 pers.</p>
<p style="text-align:center;" class="specialCase"><img src="<?php echo $this->baseUrl()?>/media/img/LI.png" alt="mazā lapa" /> Laipni lūgti viesu namā "Sidrabi"!<img src="<?php echo $this->baseUrl()?>/media/img/LI.png" alt="mazā lapa" /></p>
