<div id="rightHeader">
<div id="rightHorMenu">
<ul id="verlist">
<li><a href="/main/home?saturs=Piedavajumi"><img src="<?php echo $this->baseUrl()?>/media/img/Piedavajums.jpg" alt="Piedāvajums" /></a></li>
<li><a href="/main/home?saturs=Pakalpojumi"><img src="<?php echo $this->baseUrl()?>/media/img/Pakalpojumi.jpg" alt="Pakalpojumi" /></a></li>
<li><a href="/main/home?saturs=ParSidrabiem"><img src="<?php echo $this->baseUrl()?>/media/img/ParSidrabiem.jpg" alt="Par Sidrabiem" /></a></li>
</ul>
</div><!--end of rightHorMenu -->
<div id="headerPromo">
<img src="<?php echo $this->baseUrl()?>/media/img/HouseHeader5.gif" alt="Sidrabu Viesunams Bilde" />
</div><!--end of headerPromo-->
</div>

<div id="announcementArea">
<img src="<?php echo $this->baseUrl()?>/media/img/Announcment2.png" alt="Sidrabu Viesunams Ciemiņa Komentāri" />
</div><!--end of AnnouncmentArea-->
