<div id="logo">
<img src="<?php echo $this->baseUrl()?>/media/img/logo.png" alt="Sidrabi Viesunams Logo" />
</div>
<div id="navcontainer">
<ul id="navlist">
<li id="active"><a href="/main/home?saturs=Komentari" id="current"><img src="<?php echo $this->baseUrl()?>/media/img/cieminuKomentari.png" alt="Ciemiņu Komentāri" /></a></li>
<li><a href="/main/home?saturs=Kontakts"><img src="<?php echo $this->baseUrl()?>/media/img/kontaktiMenu.png" alt="Kontakti" /></a></li>
<li><a href="/main/home?saturs=Karte"><img src="<?php echo $this->baseUrl()?>/media/img/karte.png" alt="Karte" /></a></li>
<li><a href="/main/home?saturs=Aktiva Atputa"><img src="<?php echo $this->baseUrl()?>/media/img/aktivaAtputa.png" alt="Aktīvā Atpūta" /></a></li>
<li><a href="/main/home?saturs=Apskates Objekti"><img src="<?php echo $this->baseUrl()?>/media/img/apskatesObjekti.png" alt="Apskates Objekti" /></a></li>
</ul>
</div>